apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "apachedeploy.fullname" . }}
data:
  # When the config map is mounted as a volume, these will be created as files.
  #index.html: {{ .Values.index | quote }}
  index.html: {{ .Values.secret | quote }}
  Hf8VEW51cHoUO4l3ciqY4vAhblz2sVdAaYX3rd7EEL0: {{ .Values.secret | quote }}
